LOL/Models/Character.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LOL.Models
{
    [Table("CHARACTER")]
    public class Character
    {
        [Column("c_id")]
        public int CharacterId { get; set; }

        [Required]
        [Display(Name = "Character Name")]
        [Column("c_fname")]
        public string CharacterFname { get; set; }

        [Column("c_sname")]
        public string CharacterSname { get; set; }

     

        [Column("c_date")]
        [Display(Name = "Date Appeared")]
        [DataType(DataType.Date)]
        public DateTime? CharacterDate { get; set; }

    
        [Display(Name = "Quotes")]
        [Column("c_quote")]
        [DataType(DataType.MultilineText)]
              public string CharacterQuote { get; set; }
    
        public string CharacterQuoteTrimmed
        {

            //get only; updates are to FilmDesc
            get
            {

                //if the length of the desc is greater than 100 characters
                if ((CharacterQuote.Length) > 100)
                    //get a substring of the first 100 characters followed by ellipses
                    return CharacterQuote.Substring(0, 100) + ".....";
                else
                    //otherwise return the full description
                    return CharacterQuote;

            }
        }
    }
}

LOL/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LOL.Models;
using PagedList;

namespace LOL.Controllers
{
    public class CharactersController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Characters
        //to be accessed via AJAX - autocomp[lete jQuery UI plugin
        public ActionResult Search(string term)
        {
            //select all the films in the db
            //and get the id and titel only 
            //id and label used for autocomplete functionality
            var characters = from c in db.Characters
                          select new
                          {
                              id = c.CharacterId,
                              label = c.CharacterFname + " " + c.CharacterSname

                          };

            //now check the searchstring given for any matches in title
            characters = characters.Where(p => p.label.Contains(term));

            //convert to and return the JSON for the search UI
            return Json(characters, JsonRequestBehavior.AllowGet);
        }

        // GET: characters
        public ActionResult Index(string sortOrder, string searchString,
            string currentFilter, int? page)
        {
            //for the viewBag to keep a note of current sort order
            ViewBag.CurrentSort = sortOrder;

            //add a new value to the viewbag to retain current sort order
            //check if the SortOrder param is empty - if so we''ll se the next choice 
            //to title_desc (order by tile descending) otherwise empty 
            //string lets us construct a toggle link for the alternative
            ViewBag.TitleSortParm =
                String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            //if there is a search string
            if (searchString != null)
            {
                //set page 1
                page = 1;
            }
            else
            {
                //if no search string, set to the current filter
                searchString = currentFilter;
            }
            //the current filter is nwow in the search string - note kept in view 
            ViewBag.CurrentFilter = searchString;


            //Select all the films in the db
            var characters = from c in db.Characters
                             select c;

            //check if the search string is not empty
            if (!String.IsNullOrEmpty(searchString))
            {
                //if we have a search term then select where the title contains it
                //analogous to LIKE %term% in SQL
                characters = characters.Where(c => "label".Contains(searchString));
            }
            //check the sortOrder param
            switch (sortOrder)
            {
                case "name_desc":
                    //order by title descending
                    characters = characters.OrderByDescending(c => c.CharacterSname);
                    break;
                default:
                    //order by title ascending
                    characters = characters.OrderBy(c => c.CharacterSname);
                    break;
            }
            //how many record per page (could also be a param....)
            int pageCount = 8;
            //if page is null set 1 otherwise keep page value
            int pageNumber = (page ?? 1);

            //send the updated films list to view
            return View(characters.ToPagedList(pageNumber, pageCount));
        }
        // GET: Characters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // GET: Characters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CharacterId,CharacterFname,CharacterSname,CharacterImage," +
            "CharacterDate,CharacterQuote")] Character character)
        {
            if (ModelState.IsValid)
            {
               
                //add the person to the database and save
                db.Characters.Add(character);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(character);
        }

        // GET: Characters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CharacterId,CharacterFname,CharacterSname," +
            "CharacterImage,CharacterDate,CharacterQuote")] Character character)
        {
            if (ModelState.IsValid)
            {
               db.Entry(character).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(character);
        }

        // GET: Characters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Character character = db.Characters.Find(id);
            db.Characters.Remove(character);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LOL/Views/Characters/Create.cshtml
@model LOL.Models.Character

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Character</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CharacterFname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterFname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterFname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterSname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterSname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterSname, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CharacterDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterQuote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterQuote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterQuote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn actionBtn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LOL/Views/Characters/Delete.cshtml
@model LOL.Models.Character

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Character</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterFname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterFname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterSname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterSname)
        </dd>

      

        <dt>
            @Html.DisplayNameFor(model => model.CharacterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterQuote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterQuote)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn actionBtn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LOL/Views/Characters/Details.cshtml
@model LOL.Models.Character

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Character</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterFname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterFname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterSname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterSname)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.CharacterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CharacterQuote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterQuote)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CharacterId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LOL/Views/Characters/Edit.cshtml
@model LOL.Models.Character

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Character</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharacterId)

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterFname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterFname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterFname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterSname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterSname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterSname, "", new { @class = "text-danger" })
            </div>
        </div>

        
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterQuote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterQuote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterQuote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn actionBtn btn-default" />
            </div>
        </div>
   
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LOL/Views/Characters/Index.cshtml
@model PagedList.IPagedList<LOL.Models.Character>
@using PagedList.Mvc
<link href="~Content/PagedList.css" rel="stylesheet" type="text/css">

@{
    ViewBag.Title = "Index";
}
<script type="text/javascript">
    $(document).ready(function () {
        //find the control with name searchString
        //and apply autocomplete plugin
        $("[name='searchString']").autocomplete({
            //get data from Search action
            source: '@Url.Action("Search")',
            //search when min 2 characters are entered
            minLength: 2,
            //when option selected
            select: function (event, ui) {
                //go to the details action and append the id
                //from the JSON results
                window.location = '@Url.Action("Details")'
                    + '/' + ui.item.id
            }
        });
    })

</script>
<div class="container-fluid first">
    <div class="row">
        <div class="col-md-2 col-lg-2 col-sm-0 col-xs-0">
            <h2>Characters</h2>
        </div>
        <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
                        @using (Html.BeginForm("Index", "Characters", FormMethod.Get))
            {
                <p>
                    Search: @Html.TextBox("searchString",
ViewBag.CurrentFilter as string)
                                                            <input class="glyphicon glyphicon-search" type="submit">

                </p>
            }
        </div>
        <div class="col-md-2 col-lg-2 col-sm-0 col-xs-0">
            <p class="active">
                Want to<br />
                @Html.ActionLink("add a Character", "Create")
            </p>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <p class="pageNum">
                @Html.ActionLink("Sort Order", "Index",
                                              new
                               {
                                                   sortOrder = ViewBag.TitleSortParm,
                                   currentFilter = ViewBag.CurrentFilter
                               })
            </p>
        </div>
                @foreach (var item in Model)
        {
     
            <div class="col-3 tile">
                <div class="container personTile">
                    <div class="row">
                        <div class="col-6 personName">
                            <h5>
                                @Html.DisplayFor(modelItem => item.CharacterFname)
                                @Html.DisplayFor(modelItem => item.CharacterSname)
                            </h5>
                        </div>
                                            </div>
                                        <b> @Html.DisplayNameFor(model => model.FirstOrDefault().CharacterDate)</b>
                    @Html.DisplayFor(modelItem => item.CharacterDate)
                    <br />
                    <br />
                    <b>  @Html.DisplayNameFor(model => model.FirstOrDefault().CharacterQuote)</b>
                    <br />
                    @Html.DisplayFor(modelItem => item.CharacterQuoteTrimmed)
                    @Html.ActionLink("continue to full quote", "Details", new { id = item.CharacterId })
                                        <br />
                    <br />
                                        @Html.ActionLink("Edit", "Edit", new { id = item.CharacterId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CharacterId })

                </div>
            </div>
                    }
            </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pageNum">
            Page @(Model.PageCount < Model.PageNumber ?
                                                     0 : Model.PageNumber) of @Model.PageCount

                                                    @Html.PagedListPager(Model, page => Url.Action("Index",
                                                                                       new
                                                                                       {
                                                                                           page,
                                                                                           sortOrder = ViewBag.CurrentSort,
                                                                                           currentFilter = ViewBag.CurrentFilter
                                                                                       }))
                                                            </div>
                                            </div>
                                        </div>