LOL/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LOL.Models;
using PagedList;

namespace LOL.Controllers
{
    public class PersonsController : Controller
    {
        private DBContext db = new DBContext();

  

//to be accessed via AJAX - autocomp[lete jQuery UI plugin
        public ActionResult Search(string term)
        {
            //select all the films in the db
            //and get the id and titel only 
            //id and label used for autocomplete functionality
            var persons = from p in db.Persons
                          select new
                          {
                              id = p.PersonId,
                              label = p.PersonFname + " " + p.PersonSname

                          };

            //now check the searchstring given for any matches in title
            persons = persons.Where(p => p.label.Contains(term));

            //convert to and return the JSON for the search UI
            return Json(persons, JsonRequestBehavior.AllowGet);
        }

        // GET: persons
        public ActionResult Index(string sortOrder, string searchString,
            string currentFilter, int? page)
        {
            //for the viewBag to keep a note of current sort order
            ViewBag.CurrentSort = sortOrder;

            //add a new value to the viewbag to retain current sort order
            //check if the SortOrder param is empty - if so we''ll se the next choice 
            //to title_desc (order by tile descending) otherwise empty 
            //string lets us construct a toggle link for the alternative
            ViewBag.TitleSortParm =
                String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            //if there is a search string
            if (searchString != null)
            {
                //set page 1
                page = 1;
            }
            else
            {
                //if no search string, set to the current filter
                searchString = currentFilter;
            }
            //the current filter is nwow in the search string - note kept in view 
            ViewBag.CurrentFilter = searchString;


            //Select all the films in the db
            var persons = from p in db.Persons
                          select p;

            //check if the search string is not empty
            if (!String.IsNullOrEmpty(searchString))
            {
                //if we have a search term then select where the title contains it
                //analogous to LIKE %term% in SQL
                persons = persons.Where(p => "label".Contains(searchString));
            }
            //check the sortOrder param
            switch (sortOrder)
            {
                case "name_desc":
                    //order by title descending
                    persons = persons.OrderByDescending(p => p.PersonSname);
                    break;
                default:
                    //order by title ascending
                    persons = persons.OrderBy(p => p.PersonSname);
                    break;
            }
            //how many record per page (could also be a param....)
            int pageCount = 8;
            //if page is null set 1 otherwise keep page value
            int pageNumber = (page ?? 1);

            //send the updated films list to view
            return View(persons.ToPagedList(pageNumber, pageCount));
        }
        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonId,PersonFname,PersonSname," +
            "DateOfBirth,PersonDesc,PersonImage")] Person person,
                HttpPostedFileBase upload)
        {
            //if we have valid data in the form
            if (ModelState.IsValid)
            {
                //check to see if the file has been uploaded
                if (upload != null && upload.ContentLength > 0)
                {
                    //check to see if valid MIME type (jpg / png or gif image)
                    if (upload.ContentType == "image/jpeg" ||
                        upload.ContentType == "image/jpg" ||
                        upload.ContentType == "image/gif" ||
                        upload.ContentType == "image/png")
                    {
                        //construct A PATH TO put the file in an Images subfolder in Content
                        string path = Path.Combine(Server.MapPath("~/Content/Images/"),
                            Path.GetFileName(upload.FileName));

        //save the file to that path location
        upload.SaveAs(path);

                        //store the relative path tro the image in the database
                        person.PersonImage = "~/Content/Images/" +
                            Path.GetFileName(upload.FileName);
                    }
                    else
                    {
                        //construct a message that can be displayed in tech view
                        ViewBag.Message = "Not valid image Format";
                    }
                }
                //add the person to the database and save
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonId,PersonFname,PersonSname,DateOfBirth," +
            "PersonDesc,PersonImage")] Person person,
            HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //check to see if the file has been uploaded
                if (upload != null && upload.ContentLength > 0)
                {
                    //check to see if valid MIME type (jpg / png or gif image)
                    if (upload.ContentType == "image/jpeg" ||
                        upload.ContentType == "image/jpg" ||
                        upload.ContentType == "image/gif" ||
                        upload.ContentType == "image/png")
                    {
                        //construct A PATH TO put the file in an Images subfolder in Content
                        string path = Path.Combine(Server.MapPath("~/Content/Images/"),
                            Path.GetFileName(upload.FileName));

                        //save the file to that path location
                        upload.SaveAs(path);

                        //store the relative path to the image in the database
                        person.PersonImage = "~/Content/Images/" +
                            Path.GetFileName(upload.FileName);
                    }
                    else
                    {
                        //construct a message that can be displayed in tech view
                        ViewBag.Message = "Not valid image format";
                    }
                }
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Persons.Find(id);
            db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LOL/Views/Shared/Create.cshtml
@model LOL.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Persons", null, FormMethod.Post,
    new { enctype = "mulitpart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Person</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PersonFname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonFname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonFname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonSname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonSname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonSname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" id="Image" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LOL/Views/Shared/View.cshtml

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>View</h2>


LOL/Views/Shared/_AddReview.cshtml
@model LOL.Models.Review

<script type="text/javascript">
    $(document).ready(function () {

        $('.Rating').barrating({
            theme: 'fontawesome-stars'
        });

    });
</script>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2>Add a Review</h2>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.FilmId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="hidden" name="FilmId" value="@ViewBag.FilmId" />
                            @ViewBag.FilmTitle
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.ReviewUname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ReviewUname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ReviewUname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.ReviewContent, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ReviewContent, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ReviewContent, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(model => model.ReviewRating, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select class="Rating" name="ReviewRating">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.ReviewRating, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="editLinks">
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


LOL/Views/Shared/_FilmTile.cshtml
@model LOL.Models.Film


    <div class="col-md-4 ">
        <div class="container film-tile">
            <h4 class="filmtitle">@Model.FilmTitle</h4>
            <div class="film-image">

                @if (Model.FilmImage != null)
                {
                    <img class="img-responsive imgHover" src="@Url.Content(Model.FilmImage)" width="250" />
                }
                <p class="linksTileDdetails">
                    @Html.ActionLink("More Details", "Details", new { id = Model.FilmId })

                </p>
                <h5 class="adminoptions">
                    User Options
                </h5>
                <p class="linksTileDdetails">

                    @Html.ActionLink("Edit", "Edit", new { id = Model.FilmId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = Model.FilmId })
                </p>

            </div>
        </div>
    </div>

LOL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/jquery")*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")

    <!-- star rating plugin and themes -->
    @Scripts.Render("~/Scripts/Stars/jquery.barrating.min.js")
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    @Styles.Render("~/Scripts/Stars/themes/fontawesome-stars.css")
    @Styles.Render("~/Scripts/Stars/themes/fontawesome-stars-o.css")

    <!--JQuery UI for autocomplete-->
    @Scripts.Render("~/Scripts/jquery-ui-1.12.1/jquery-ui.min.js")
    @Styles.Render("~/Scripts/jquery-ui-1.12.1/jquery-ui.min.css")
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="container-fluid headerSect ">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 logo">
                <img class="img-responsive" id="logo" src="~/Content/images/newestlogosmaller.png" width="400"/>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                <h1 class="title"><b>ARE YOU UP FOR THE CRACK?! :D</b></h1>
                <h4 class="Title1">All your best Comedy films</h4>
                        
                    </div>
                </div>
            </div>
       
   
    <nav class="navbar navbar-inverse">
       <div class="nav navbar-nav">
            @Html.ActionLink("LOL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            @Html.ActionLink("Home", "Index", "Home")
            @Html.ActionLink("Films", "Index", "Films")
           @Html.ActionLink("People", "Index", "Persons")
           </div>
    </nav>
   
          
  
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
               
            </div>
        </div>
    </div>
    <footer>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <h2 class="extralinks">USEFUL LINKS</h2>
                    <ul class="links">
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <h2 class="extralinks">FOLLOW</h2>
                    <div class="smlinks">
                        <img width="70" src="~/Content/images/youtube.png" />
                        <img width="70" src="~/Content/images/vim.png" />
                        <img width="70" src="~/Content/images/fb.png" />
                        <img width="70" src="~/Content/images/twit.png" />
                    </div>
                    <p class="cpyright">Copyright © @DateTime.Now LOL.com</p>
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <h2 class="extralinks">LEGAL</h2>
                    <ul class="links">
                        <li>T & C's</li>
                        <li>Privacy</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

LOL/Views/Shared/_Modal.cshtml
@model LOL.Models.Review

<div>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Add Review</h4>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Review</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FilmId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FilmId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FilmId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReviewUname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReviewUname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReviewUname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReviewContent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReviewContent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReviewContent, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReviewRating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReviewRating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReviewRating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

LOL/Views/Shared/_ModalLayout.cshtml
<h1>
Add a Review
</h1>
@RenderSection("scripts", required: true)
@RenderBody()

LOL/Views/Shared/_homeLayOut.cshtml
@using LOL.Models;
@model Tuple<Film, Review>
@{
    ViewBag.Title = "_homeLayOut.cshtml";
}

@section Scripts {
    @RenderSection("scripts", required: false)
}
<div>
    @RenderBody()
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
          
            <div class="container nxtSect pImage">
                <div class="row">
                    <div class="col-sm-6">
                        <h1 class="pageTitle">
                            @Html.DisplayNameFor(tuple => tuple.Item1.FilmTitle)

                        </h1>
                    </div>
                
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="name">

                            <strong> <em>  @Html.DisplayNameFor(tuple => tuple.Item1.FilmBBFC):</em></strong>
                            @Html.DisplayFor(tuple => tuple.Item1.FilmBBFC) |
                            <strong>    <em> @Html.DisplayNameFor(tuple => tuple.Item1.FilmReleaseDate):</em></strong>
                            @Html.DisplayFor(tuple => tuple.Item1.FilmReleaseDate) |
                            <strong> <em>  @Html.DisplayNameFor(tuple => tuple.Item1.FilmSequel):</em></strong>
                            @Html.DisplayFor(tuple => tuple.Item1)
                        </div>
                        <h4 class="undertitle">
                            @Html.DisplayNameFor(tuple => tuple.Item1.FilmTrailer)
                        </h4>
                    
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 ">

            @Html.DisplayNameFor(tuple => tuple.Item2.ReviewId)
            <h2>Review Details</h2>

            <div>


                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(tuple => tuple.Item1.FilmTitle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(tuple => tuple.Item1.FilmTitle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(tuple => tuple.Item2.ReviewUname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(tuple => tuple.Item2.ReviewUname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(tuple => tuple.Item2.ReviewContent)
                    </dt>

                    <dd>
                        @Html.DisplayFor(tuple => tuple.Item2.ReviewContent)
                    </dd>

                  
                </dl>
            </div>
      

        </div>
    </div>
</div>